sudo: required
dist: trusty
language: node_js
node_js:
  - '8.1.2'
  - 'stable'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  firefox: 'latest'
cache:
  directories:
    - node_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: qGlTTUgyak6BjMYK3HcX25PDB9pDX9Vv3ZTGhwJWOzD8ZOVwfASdAm1YsXyP2ov5r3LJY2Mf2RFEMCCcZa1Dl3rauUX/5agPaaz7qBgXBHYJRKtWvviuo3RwSNVBPEUIxcWnEEugY829oNygOd0P3TAW4eAOHwpCaFgHETLFRLfIu+nEp5MZKk4luz/gfls+d6fpXWbGu57gtklFKnQSMiBbPN4Eab8Z5m7yCQ/d4HFXi/HwfpZFuVo4jF0fS7k6mci9GHOI6Kr6V2nsFcvATB2lOF5Nr3rUn9xL1tHUED49Q3g44iIUa5PPHoItyIEhgcx4nz9FNA3cngTY+0DeQhxYBL5zLtOHpOB5ksqury62bCLKeFxq+umE9OlOCSxbULOb61Y/Kz7tr3JGIC6xBvZG395BQNyePye9NimkFVTT31mFNuGloT6ZlBfsQIWr/CZ7sT32u5ZCyxp3liQj+o2lBJsKqqrD2IszK0xJWn6CoBvUjOrsvUBkJqOr6zWkuVC13NnoAPR3ki9LdNksiRm/ehUWDkQDuZkbYl/chF22nGyu+9i0QlrjfYuZ7eAwxPNnJVmqb8XXORUiiPqf2IlmwqJl9n/swMq9THyMUxmYT3a+R1AwfFGYb4trqvHZs0wGhVWQdSxgfJEkK91MZrK9xwL6J6Ob1ZSdY1HbfNg=
before_install:
  - npm config set spin false
  - npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh
install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh
after_success:
  - $(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh
after_deploy:
- $(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: ub6ykDXPrOcwkBDCFl5ldAfKNn4wvyEyZ+vXl6rmYf1NTkahgzUkIcQgtaY5a25mDeYSCzqDUacWgfFy8SBL4kd1NQKw9kkzq7hZ6DEaLR5IhrUlH+evQWixmM2x9KgEr6m7XybYbPK0scGhFszDD13yTEguhuO4oA2lGUHr1XiwmiDkjzgr31veL5ioCPrQCiwQzgufpmshJ886XgkcDP1veR4o79pDQr5IgtPuZ1aHuHHwy6Iqzn0tc5t4lLmFZ5urv2nUUzOP9hCfqh9UuJHrc3Ovw6FpklZjpQMxuOhS8SYwy3A7I2mAtI0szS0g7pYRaiCN5KQbdyzVUhPsao5exvUbIYo8NZ1zWrFSKxnh+g2r+Dpz03Kxdh6u9EE1nLgv5qe4loKT74EzUGUPmMl+OONjOgFlD2058WYIDGWPdUWMMSWSRAorS4TJOqxHe/p3ENhhiALWjyNv5tHZ2knuIM+PWqtmkg5EcaPNM7Va5NY/gUsDhfkaVaw3F+CZT3szAvqSgVTB9LK2sFuK/MrsIYMwl4UW1T3V2FQ415K/EsZxSgd/S1roFGevrbSy9GzZSO2DV7vuq52YWWxTBuZTR0APmM4Y+ZRP4qYURIngARkfSG1Sl3cQi7Ps163k5wxwdy6GpPXkoUSy6h32LAnVyrPO0xA1pOXmvCR0YxU=
  on:
    all_branches: true
    node: '8.1.2'
    tags: true
notifications:
  slack:
    secure: loy1WAcGRiPsU6jOQfrTlg7zlyVwH5F5k5zg8rYVEqQhXMVthYhBcqgRMnsXOGAajlqASewU4RiwEP7bcNrj3RU2KnChlHzatBS4MsspPPLRwLYJmlVEja7t0/x6PdXT8CUbfi6it7bTfRSleUhTPzDpXSaRP8t6EXi66Pjiu5gIX2H0Z1DQi6iwQYpJgvIIiHFqCbsJzWXLdl24ymWGRRfR8fF0kQowbB1yVBLiPc6kp84KEZJXDhAOsswYsxaXiqOfOGZ/aSaruqjKVzWd71RE1RL6+Ot+zTz9Kj3BNvz93Fq47uGLr/wPceHGUICX6EyaOcfrKH0Qa2wJM2OqWndyw61A1kAXLMVYuUNvMk3GboisGuZLQvkvtd4uMWqdjBeS1JgLiOyoHhqnFzlhvYGT8/iGZuJdhPuQYmYnwJdGtPHimYdTKxpQ/d5eZJdhh8GHzaL5GyGDrnnVHz6OeBbkgN3zbPecQeWhYuMpLkVXQgDUbxbpVFMJgNkU+noSmhCSfO3dfQjIl7DsgduG2iZYRr14UNAP5jNSsCn/r/WntIrfrqEQMJOTAIAWIYw4b+equ2Y7Xy0ki4QHcQBMGTYoAIDDi90nYSXzjxr9NO5bazTooQfELYX0riYpBdKr6WKbOoqfnbb/EymwCoOgdzLGHAb5e4XtoVZ8+EMxZU8=
