sudo: required
dist: trusty
language: node_js
node_js:
- 8.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  firefox: latest
cache:
  directories:
  - node_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: qGlTTUgyak6BjMYK3HcX25PDB9pDX9Vv3ZTGhwJWOzD8ZOVwfASdAm1YsXyP2ov5r3LJY2Mf2RFEMCCcZa1Dl3rauUX/5agPaaz7qBgXBHYJRKtWvviuo3RwSNVBPEUIxcWnEEugY829oNygOd0P3TAW4eAOHwpCaFgHETLFRLfIu+nEp5MZKk4luz/gfls+d6fpXWbGu57gtklFKnQSMiBbPN4Eab8Z5m7yCQ/d4HFXi/HwfpZFuVo4jF0fS7k6mci9GHOI6Kr6V2nsFcvATB2lOF5Nr3rUn9xL1tHUED49Q3g44iIUa5PPHoItyIEhgcx4nz9FNA3cngTY+0DeQhxYBL5zLtOHpOB5ksqury62bCLKeFxq+umE9OlOCSxbULOb61Y/Kz7tr3JGIC6xBvZG395BQNyePye9NimkFVTT31mFNuGloT6ZlBfsQIWr/CZ7sT32u5ZCyxp3liQj+o2lBJsKqqrD2IszK0xJWn6CoBvUjOrsvUBkJqOr6zWkuVC13NnoAPR3ki9LdNksiRm/ehUWDkQDuZkbYl/chF22nGyu+9i0QlrjfYuZ7eAwxPNnJVmqb8XXORUiiPqf2IlmwqJl9n/swMq9THyMUxmYT3a+R1AwfFGYb4trqvHZs0wGhVWQdSxgfJEkK91MZrK9xwL6J6Ob1ZSdY1HbfNg=
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
- "$(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh"
install:
- "$(npm root -g)/pr-bumper/.travis/maybe-install.sh"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- "$(npm root -g)/pr-bumper/.travis/maybe-test.sh"
- "$(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh"
after_success:
- "$(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh"
after_deploy:
- "$(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh"
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: NzSHoekx1UdKBiHkS06/AfF2C6YLDSlHT7LxSBmHAECEEaQn0AQqR0f5Z5woL2tJw/HWX3zlOd91vFnIsTTfetmr29hhsN0GCw2wFlmDy9Igu4/Jb0tQ1B6guKs7Lf1UE564pn7M38cLQoiBSAwWBrnD1UOFQ4oEE6k2kuI2oU5ZIjAzKQUdYdmrg6mGGO9x77WE4TVs/+gHmobVaR07sjNFwa8iPIx0JYYzNyuhRhTOgV8UZJP+2GkCkDgk03bwlttGelmL1z0sirakPdoCGdAGtLLn3FPd4shNibI0Qu1c2ULXyjueDncjtMJJNwfnzTxOcUSsIhuzRrVOjb+n1D+RrCKMLuT3PwXC4FNpds8KfBIfZSH8K86lX5SY3FUEtDRZ2BIXVRYnJB5vS+/ViDDrpxE3oVvSgtIKcqABkMgerZFEo4EIQUoGrVah0ZjxmY6dDyLVj+ddTJ839RRqLvclAEds8qloUp3Flj9Gs/KfAkNN2CKTNOB+EDd1eXrSYB7E2ZgPJDMgSpyzLydPB7l85Sa6cBr5hDJVkF1cNrjiVc8L+iat+xxK6B0s9nsjR5zZxwp6A+72KPjhE/n7Bhk1FBKT6pSKdXPasFG+tpOU01ZHygWtm4tWdFipmzi/Nb3b2n/cb8GDiPeSLuoACjdGqfx8hUWNBG7W47Y7vkk=
  on:
    all_branches: true
    node: 8.6.0
    tags: true
notifications:
  slack:
    secure: loy1WAcGRiPsU6jOQfrTlg7zlyVwH5F5k5zg8rYVEqQhXMVthYhBcqgRMnsXOGAajlqASewU4RiwEP7bcNrj3RU2KnChlHzatBS4MsspPPLRwLYJmlVEja7t0/x6PdXT8CUbfi6it7bTfRSleUhTPzDpXSaRP8t6EXi66Pjiu5gIX2H0Z1DQi6iwQYpJgvIIiHFqCbsJzWXLdl24ymWGRRfR8fF0kQowbB1yVBLiPc6kp84KEZJXDhAOsswYsxaXiqOfOGZ/aSaruqjKVzWd71RE1RL6+Ot+zTz9Kj3BNvz93Fq47uGLr/wPceHGUICX6EyaOcfrKH0Qa2wJM2OqWndyw61A1kAXLMVYuUNvMk3GboisGuZLQvkvtd4uMWqdjBeS1JgLiOyoHhqnFzlhvYGT8/iGZuJdhPuQYmYnwJdGtPHimYdTKxpQ/d5eZJdhh8GHzaL5GyGDrnnVHz6OeBbkgN3zbPecQeWhYuMpLkVXQgDUbxbpVFMJgNkU+noSmhCSfO3dfQjIl7DsgduG2iZYRr14UNAP5jNSsCn/r/WntIrfrqEQMJOTAIAWIYw4b+equ2Y7Xy0ki4QHcQBMGTYoAIDDi90nYSXzjxr9NO5bazTooQfELYX0riYpBdKr6WKbOoqfnbb/EymwCoOgdzLGHAb5e4XtoVZ8+EMxZU8=
